Calling String(Bottle) causes a compile error here. Fix by using Bottle.name directly.
Errors were:
src/sketch.ino:175:5: error: no matching function for call to 'HardwareSerial::print(Bottle&)'